--------------------------------------------------------
--  Fichier créé - lundi-janvier-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AGENCE
--------------------------------------------------------

  CREATE TABLE "ROSTOM"."AGENCE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"D" DATE, 
	"EMPLOYER" NUMBER, 
	"DIRECTEUR" NUMBER, 
	"VENTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ASSURANCE
--------------------------------------------------------

  CREATE TABLE "ROSTOM"."ASSURANCE" 
   (	"COMPAGNIE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"REFERENCE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHAINE
--------------------------------------------------------

  CREATE TABLE "ROSTOM"."CHAINE" 
   (	"REFERENCE" VARCHAR2(20 BYTE), 
	"NB_MACHINE" VARCHAR2(20 BYTE), 
	"TYPE_PRODUIT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "ROSTOM"."CLIENT" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(20 BYTE), 
	"ACHAT" VARCHAR2(20 BYTE), 
	"PAIEMENT" VARCHAR2(20 BYTE), 
	"DATE_NAISSANCE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "ROSTOM"."FOURNISSEUR" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"PIECE_DEMANDEE" VARCHAR2(20 BYTE), 
	"NBRE_PIECE" VARCHAR2(20 BYTE), 
	"PRIX_APAYER" NUMBER, 
	"DATELIMITE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARKING
--------------------------------------------------------

  CREATE TABLE "ROSTOM"."PARKING" 
   (	"REFERENCE" NUMBER, 
	"PLACE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TABLE1
--------------------------------------------------------

  CREATE TABLE "ROSTOM"."TABLE1" 
   (	"CIN" NUMBER(20,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"SALAIRE" NUMBER, 
	"POSTE" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"NOMBRE" NUMBER, 
	"ADRESSE" VARCHAR2(200 BYTE), 
	"PASSE" VARCHAR2(200 BYTE), 
	"RFID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POINTAGE
--------------------------------------------------------

  CREATE TABLE "ROSTOM"."POINTAGE" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(40 BYTE), 
	"PRENOM" VARCHAR2(40 BYTE), 
	"D" DATE, 
	"TIME" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VOITURE1
--------------------------------------------------------

  CREATE TABLE "ROSTOM"."VOITURE1" 
   (	"REFERENCE" VARCHAR2(20 BYTE), 
	"MARQUE" VARCHAR2(20 BYTE), 
	"MODELE" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"PRIX_OPTION" VARCHAR2(20 BYTE), 
	"COULEUR" VARCHAR2(20 BYTE), 
	"OPTIONS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ROSTOM.AGENCE
SET DEFINE OFF;
Insert into ROSTOM.AGENCE (ID,NOM,ADRESSE,D,EMPLOYER,DIRECTEUR,VENTE) values ('tx','agence ridha','15 tunis',to_date('01-01-00','DD-MM-RR'),20,14,40);
Insert into ROSTOM.AGENCE (ID,NOM,ADRESSE,D,EMPLOYER,DIRECTEUR,VENTE) values ('fr','agence souad','25 tunis',to_date('01-01-99','DD-MM-RR'),30,17,14);
Insert into ROSTOM.AGENCE (ID,NOM,ADRESSE,D,EMPLOYER,DIRECTEUR,VENTE) values ('rt700','rz','ryry',to_date('01-01-00','DD-MM-RR'),0,888,0);
REM INSERTING into ROSTOM.ASSURANCE
SET DEFINE OFF;
Insert into ROSTOM.ASSURANCE (COMPAGNIE,TYPE,PRIX,REFERENCE) values ('l','p',1,1);
REM INSERTING into ROSTOM.CHAINE
SET DEFINE OFF;
Insert into ROSTOM.CHAINE (REFERENCE,NB_MACHINE,TYPE_PRODUIT) values ('1','1','a');
REM INSERTING into ROSTOM.CLIENT
SET DEFINE OFF;
Insert into ROSTOM.CLIENT (CIN,PRENOM,NOM,MODEL,ACHAT,PAIEMENT,DATE_NAISSANCE) values ('78','aze','aze','aze','785','454545',to_date('01-01-00','DD-MM-RR'));
REM INSERTING into ROSTOM.FOURNISSEUR
SET DEFINE OFF;
Insert into ROSTOM.FOURNISSEUR (CIN,NOM,PRENOM,PIECE_DEMANDEE,NBRE_PIECE,PRIX_APAYER,DATELIMITE) values (123,'az','r','fr','78',2131,to_date('01-01-00','DD-MM-RR'));
REM INSERTING into ROSTOM.PARKING
SET DEFINE OFF;
Insert into ROSTOM.PARKING (REFERENCE,PLACE,NOM) values (111,1111,'aza');
REM INSERTING into ROSTOM.TABLE1
SET DEFINE OFF;
Insert into ROSTOM.TABLE1 (CIN,NOM,PRENOM,SALAIRE,POSTE,ETAT,NOMBRE,ADRESSE,PASSE,RFID) values (20,'aderssa','dhia',2000,'employer','SINGLE',0,'aderssa.dhia.factory@gmail.com','15621562','F79414AF');
Insert into ROSTOM.TABLE1 (CIN,NOM,PRENOM,SALAIRE,POSTE,ETAT,NOMBRE,ADRESSE,PASSE,RFID) values (77,'dhta','tat',8787,'taat','SINGLE',44,'dhta.tat.factory@gamil.com','77447744','hmd');
Insert into ROSTOM.TABLE1 (CIN,NOM,PRENOM,SALAIRE,POSTE,ETAT,NOMBRE,ADRESSE,PASSE,RFID) values (143,'charni','rostom',10000,'administrateur','MARRIED',3,'ros.ch.factory@gmail.com','1433','74C9CB5');
REM INSERTING into ROSTOM.POINTAGE
SET DEFINE OFF;
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (20,'aderssa','dhia',to_date('30-12-20','DD-MM-RR'),'23:03:38');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (20,'aderssa','dhia',to_date('30-12-20','DD-MM-RR'),'23:03:55');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (143,'charni','rostom',to_date('30-12-20','DD-MM-RR'),'23:04:07');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (143,'charni','rostom',to_date('30-12-20','DD-MM-RR'),'23:04:27');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (143,'charni','rostom',to_date('30-12-20','DD-MM-RR'),'23:05:30');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (20,'aderssa','dhia',to_date('30-12-20','DD-MM-RR'),'23:07:20');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (20,'aderssa','dhia',to_date('30-12-20','DD-MM-RR'),'23:08:29');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (143,'charni','rostom',to_date('30-12-20','DD-MM-RR'),'23:12:16');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (20,'aderssa','dhia',to_date('30-12-20','DD-MM-RR'),'23:12:39');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (143,'charni','rostom',to_date('30-12-20','DD-MM-RR'),'23:13:55');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (143,'charni','rostom',to_date('30-12-20','DD-MM-RR'),'23:14:46');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (20,'aderssa','dhia',to_date('30-12-20','DD-MM-RR'),'23:15:00');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (143,'charni','rostom',to_date('30-12-20','DD-MM-RR'),'23:16:22');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (20,'aderssa','dhia',to_date('30-12-20','DD-MM-RR'),'23:16:33');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (143,'charni','rostom',to_date('30-12-20','DD-MM-RR'),'23:32:25');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (20,'aderssa','dhia',to_date('30-12-20','DD-MM-RR'),'23:32:39');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (143,'charni','rostom',to_date('30-12-20','DD-MM-RR'),'23:35:38');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (20,'aderssa','dhia',to_date('30-12-20','DD-MM-RR'),'23:36:38');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (143,'charni','rostom',to_date('30-12-20','DD-MM-RR'),'23:37:13');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (143,'charni','rostom',to_date('02-01-21','DD-MM-RR'),'22:53:51');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (143,'charni','rostom',to_date('30-12-20','DD-MM-RR'),'23:02:13');
Insert into ROSTOM.POINTAGE (CIN,NOM,PRENOM,D,TIME) values (20,'aderssa','dhia',to_date('30-12-20','DD-MM-RR'),'23:03:27');
REM INSERTING into ROSTOM.VOITURE1
SET DEFINE OFF;
Insert into ROSTOM.VOITURE1 (REFERENCE,MARQUE,MODELE,PRIX,TYPE,PRIX_OPTION,COULEUR,OPTIONS) values ('11','z','d',1,'f','1','j','gf');
--------------------------------------------------------
--  DDL for Index ASSURANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROSTOM"."ASSURANCE_PK" ON "ROSTOM"."ASSURANCE" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARKING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROSTOM"."PARKING_PK" ON "ROSTOM"."PARKING" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AGENCE
--------------------------------------------------------

  ALTER TABLE "ROSTOM"."AGENCE" MODIFY ("VENTE" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."AGENCE" MODIFY ("DIRECTEUR" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."AGENCE" MODIFY ("EMPLOYER" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."AGENCE" MODIFY ("D" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."AGENCE" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."AGENCE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."AGENCE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASSURANCE
--------------------------------------------------------

  ALTER TABLE "ROSTOM"."ASSURANCE" ADD CONSTRAINT "ASSURANCE_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROSTOM"."ASSURANCE" MODIFY ("REFERENCE" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."ASSURANCE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."ASSURANCE" MODIFY ("COMPAGNIE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHAINE
--------------------------------------------------------

  ALTER TABLE "ROSTOM"."CHAINE" MODIFY ("TYPE_PRODUIT" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."CHAINE" MODIFY ("NB_MACHINE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "ROSTOM"."CLIENT" MODIFY ("DATE_NAISSANCE" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."CLIENT" MODIFY ("PAIEMENT" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."CLIENT" MODIFY ("ACHAT" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."CLIENT" MODIFY ("MODEL" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."CLIENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."CLIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "ROSTOM"."FOURNISSEUR" MODIFY ("DATELIMITE" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."FOURNISSEUR" MODIFY ("PRIX_APAYER" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."FOURNISSEUR" MODIFY ("NBRE_PIECE" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."FOURNISSEUR" MODIFY ("PIECE_DEMANDEE" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."FOURNISSEUR" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."FOURNISSEUR" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARKING
--------------------------------------------------------

  ALTER TABLE "ROSTOM"."PARKING" ADD CONSTRAINT "PARKING_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROSTOM"."PARKING" MODIFY ("REFERENCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TABLE1
--------------------------------------------------------

  ALTER TABLE "ROSTOM"."TABLE1" MODIFY ("RFID" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."TABLE1" MODIFY ("PASSE" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."TABLE1" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."TABLE1" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."TABLE1" MODIFY ("ETAT" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."TABLE1" MODIFY ("POSTE" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."TABLE1" MODIFY ("SALAIRE" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."TABLE1" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."TABLE1" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."TABLE1" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POINTAGE
--------------------------------------------------------

  ALTER TABLE "ROSTOM"."POINTAGE" MODIFY ("TIME" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."POINTAGE" MODIFY ("D" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."POINTAGE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."POINTAGE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."POINTAGE" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOITURE1
--------------------------------------------------------

  ALTER TABLE "ROSTOM"."VOITURE1" MODIFY ("OPTIONS" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."VOITURE1" MODIFY ("COULEUR" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."VOITURE1" MODIFY ("PRIX_OPTION" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."VOITURE1" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."VOITURE1" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."VOITURE1" MODIFY ("MODELE" NOT NULL ENABLE);
  ALTER TABLE "ROSTOM"."VOITURE1" MODIFY ("MARQUE" NOT NULL ENABLE);
