--------------------------------------------------------
--  Fichier créé - mercredi-décembre-16-2020   
--------------------------------------------------------
DROP TABLE "MAYSSA"."AGENCE";
DROP TABLE "MAYSSA"."ASSURANCE";
DROP TABLE "MAYSSA"."CHAINE";
DROP TABLE "MAYSSA"."CLIENT";
DROP TABLE "MAYSSA"."FOURNISSEUR";
DROP TABLE "MAYSSA"."PARKING";
DROP TABLE "MAYSSA"."TABLE1";
DROP TABLE "MAYSSA"."VOITURE1";
--------------------------------------------------------
--  DDL for Table AGENCE
--------------------------------------------------------

  CREATE TABLE "MAYSSA"."AGENCE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"D" DATE, 
	"EMPLOYER" NUMBER, 
	"DIRECTEUR" NUMBER, 
	"VENTE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ASSURANCE
--------------------------------------------------------

  CREATE TABLE "MAYSSA"."ASSURANCE" 
   (	"COMPAGNIE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"REFERENCE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHAINE
--------------------------------------------------------

  CREATE TABLE "MAYSSA"."CHAINE" 
   (	"REFERENCE" VARCHAR2(20 BYTE), 
	"NB_MACHINE" NUMBER, 
	"TYPE_PRODUIT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "MAYSSA"."CLIENT" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(20 BYTE), 
	"ACHAT" VARCHAR2(20 BYTE), 
	"PAIEMENT" VARCHAR2(20 BYTE), 
	"DATE_NAISSANCE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "MAYSSA"."FOURNISSEUR" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"PIECE_DEMANDEE" VARCHAR2(20 BYTE), 
	"NBRE_PIECE" VARCHAR2(20 BYTE), 
	"PRIX_APAYER" NUMBER, 
	"DATELIMITE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARKING
--------------------------------------------------------

  CREATE TABLE "MAYSSA"."PARKING" 
   (	"REFERENCE" VARCHAR2(20 BYTE), 
	"PLACE" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TABLE1
--------------------------------------------------------

  CREATE TABLE "MAYSSA"."TABLE1" 
   (	"CIN" NUMBER(20,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"SALAIRE" VARCHAR2(20 BYTE), 
	"POSTE" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"NOMBRE" NUMBER(20,0), 
	"ADRESSE" VARCHAR2(50 BYTE), 
	"PASSE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VOITURE1
--------------------------------------------------------

  CREATE TABLE "MAYSSA"."VOITURE1" 
   (	"REFERENCE" VARCHAR2(20 BYTE), 
	"MARQUE" VARCHAR2(20 BYTE), 
	"MODELE" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"PRIX_OPTION" NUMBER, 
	"COULEUR" VARCHAR2(20 BYTE), 
	"OPTIONS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MAYSSA.AGENCE
SET DEFINE OFF;
Insert into MAYSSA.AGENCE (ID,NOM,ADRESSE,D,EMPLOYER,DIRECTEUR,VENTE) values ('8765','mayssa','kjhgfdjk',to_date('08/01/00','DD/MM/RR'),'4','20','3');
Insert into MAYSSA.AGENCE (ID,NOM,ADRESSE,D,EMPLOYER,DIRECTEUR,VENTE) values ('666','mayssa','kjhgfdjk',to_date('08/01/00','DD/MM/RR'),'4','20','3');
REM INSERTING into MAYSSA.ASSURANCE
SET DEFINE OFF;
REM INSERTING into MAYSSA.CHAINE
SET DEFINE OFF;
Insert into MAYSSA.CHAINE (REFERENCE,NB_MACHINE,TYPE_PRODUIT) values ('222','100','sakli');
Insert into MAYSSA.CHAINE (REFERENCE,NB_MACHINE,TYPE_PRODUIT) values ('123','2','mayssa');
Insert into MAYSSA.CHAINE (REFERENCE,NB_MACHINE,TYPE_PRODUIT) values ('321','442','eyaaa');
Insert into MAYSSA.CHAINE (REFERENCE,NB_MACHINE,TYPE_PRODUIT) values ('555','10','bouton');
Insert into MAYSSA.CHAINE (REFERENCE,NB_MACHINE,TYPE_PRODUIT) values ('666','2','doudou');
Insert into MAYSSA.CHAINE (REFERENCE,NB_MACHINE,TYPE_PRODUIT) values ('987','9','hola');
Insert into MAYSSA.CHAINE (REFERENCE,NB_MACHINE,TYPE_PRODUIT) values ('432','6','guidon');
REM INSERTING into MAYSSA.CLIENT
SET DEFINE OFF;
Insert into MAYSSA.CLIENT (CIN,NOM,PRENOM,MODEL,ACHAT,PAIEMENT,DATE_NAISSANCE) values ('65432','mayssa','bb','KOJIHUY','543','654','01/01/2000');
REM INSERTING into MAYSSA.FOURNISSEUR
SET DEFINE OFF;
Insert into MAYSSA.FOURNISSEUR (CIN,NOM,PRENOM,PIECE_DEMANDEE,NBRE_PIECE,PRIX_APAYER,DATELIMITE) values ('45678','mayssa','uiy','kjh','66','987','01/01/2000');
REM INSERTING into MAYSSA.PARKING
SET DEFINE OFF;
REM INSERTING into MAYSSA.TABLE1
SET DEFINE OFF;
Insert into MAYSSA.TABLE1 (CIN,NOM,PRENOM,SALAIRE,POSTE,ETAT,NOMBRE,ADRESSE,PASSE) values ('20','aderssa','dhia','200','employer','SINGLE','0','aderssa.dhia.factory@gmail.com','15621562');
Insert into MAYSSA.TABLE1 (CIN,NOM,PRENOM,SALAIRE,POSTE,ETAT,NOMBRE,ADRESSE,PASSE) values ('143','ros','ch','10','administrateur','MARRIED','3','ros.ch.factory@gmail.com','1433');
Insert into MAYSSA.TABLE1 (CIN,NOM,PRENOM,SALAIRE,POSTE,ETAT,NOMBRE,ADRESSE,PASSE) values ('777','mlkjhgf','oikujyht','543','234','SINGLE','2','mlkjhgf.oikujyht.factory@gamil.com','77727772');
REM INSERTING into MAYSSA.VOITURE1
SET DEFINE OFF;
Insert into MAYSSA.VOITURE1 (REFERENCE,MARQUE,MODELE,PRIX,TYPE,PRIX_OPTION,COULEUR,OPTIONS) values ('123','bmw','mayssa','555','essance','99','jaune','sportif');
Insert into MAYSSA.VOITURE1 (REFERENCE,MARQUE,MODELE,PRIX,TYPE,PRIX_OPTION,COULEUR,OPTIONS) values ('3455','fiat','punto','334','essance','555','rouge','sportif');
Insert into MAYSSA.VOITURE1 (REFERENCE,MARQUE,MODELE,PRIX,TYPE,PRIX_OPTION,COULEUR,OPTIONS) values ('12345','ldjzoijd','jsopdj','444','dejiuy','3332','jaune','jh');
Insert into MAYSSA.VOITURE1 (REFERENCE,MARQUE,MODELE,PRIX,TYPE,PRIX_OPTION,COULEUR,OPTIONS) values ('888','kia','sportege','555555','gasoil','9','noir','sportif');
Insert into MAYSSA.VOITURE1 (REFERENCE,MARQUE,MODELE,PRIX,TYPE,PRIX_OPTION,COULEUR,OPTIONS) values ('55','kia','hahah','33','essance','9999','jaune','sportif');
Insert into MAYSSA.VOITURE1 (REFERENCE,MARQUE,MODELE,PRIX,TYPE,PRIX_OPTION,COULEUR,OPTIONS) values ('12776','maay','llla','665','hhhhh','33','llla','ee');
--------------------------------------------------------
--  DDL for Index AGENCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAYSSA"."AGENCE_PK" ON "MAYSSA"."AGENCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ASSURANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAYSSA"."ASSURANCE_PK" ON "MAYSSA"."ASSURANCE" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHAINE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAYSSA"."CHAINE_PK" ON "MAYSSA"."CHAINE" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAYSSA"."CLIENT_PK" ON "MAYSSA"."CLIENT" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNISSEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAYSSA"."FOURNISSEUR_PK" ON "MAYSSA"."FOURNISSEUR" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARKING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAYSSA"."PARKING_PK" ON "MAYSSA"."PARKING" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAYSSA"."TABLE1_PK" ON "MAYSSA"."TABLE1" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VOITURE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAYSSA"."VOITURE1_PK" ON "MAYSSA"."VOITURE1" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AGENCE
--------------------------------------------------------

  ALTER TABLE "MAYSSA"."AGENCE" ADD CONSTRAINT "AGENCE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAYSSA"."AGENCE" MODIFY ("VENTE" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."AGENCE" MODIFY ("DIRECTEUR" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."AGENCE" MODIFY ("EMPLOYER" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."AGENCE" MODIFY ("D" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."AGENCE" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."AGENCE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."AGENCE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASSURANCE
--------------------------------------------------------

  ALTER TABLE "MAYSSA"."ASSURANCE" ADD CONSTRAINT "ASSURANCE_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAYSSA"."ASSURANCE" MODIFY ("REFERENCE" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."ASSURANCE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."ASSURANCE" MODIFY ("COMPAGNIE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHAINE
--------------------------------------------------------

  ALTER TABLE "MAYSSA"."CHAINE" ADD CONSTRAINT "CHAINE_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAYSSA"."CHAINE" MODIFY ("REFERENCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "MAYSSA"."CLIENT" MODIFY ("MODEL" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."CLIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."CLIENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."CLIENT" MODIFY ("DATE_NAISSANCE" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."CLIENT" MODIFY ("PAIEMENT" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."CLIENT" MODIFY ("ACHAT" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAYSSA"."CLIENT" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "MAYSSA"."FOURNISSEUR" ADD CONSTRAINT "FOURNISSEUR_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAYSSA"."FOURNISSEUR" MODIFY ("DATELIMITE" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."FOURNISSEUR" MODIFY ("PRIX_APAYER" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."FOURNISSEUR" MODIFY ("NBRE_PIECE" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."FOURNISSEUR" MODIFY ("PIECE_DEMANDEE" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."FOURNISSEUR" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."FOURNISSEUR" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARKING
--------------------------------------------------------

  ALTER TABLE "MAYSSA"."PARKING" ADD CONSTRAINT "PARKING_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAYSSA"."PARKING" MODIFY ("REFERENCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TABLE1
--------------------------------------------------------

  ALTER TABLE "MAYSSA"."TABLE1" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAYSSA"."TABLE1" MODIFY ("PASSE" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."TABLE1" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."TABLE1" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."TABLE1" MODIFY ("ETAT" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."TABLE1" MODIFY ("POSTE" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."TABLE1" MODIFY ("SALAIRE" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."TABLE1" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."TABLE1" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "MAYSSA"."TABLE1" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOITURE1
--------------------------------------------------------

  ALTER TABLE "MAYSSA"."VOITURE1" ADD CONSTRAINT "VOITURE1_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAYSSA"."VOITURE1" MODIFY ("REFERENCE" NOT NULL ENABLE);
